[[flash]]
address = 0x2000_0000
size = 0x8_0000 
read = true
execute = true

[[ram]]
address = 0x1000_0000
size = 0x1_0000 
read = true
write = true
execute = false  # let's assume XN until proven otherwise
