[package]
name = "task-sp-measure"
version = "0.1.0"
edition = "2018"

[dependencies]
userlib = {path = "../../sys/userlib", features = ["panic-messages"]}
ringbuf = {path = "../../lib/ringbuf"}
drv-sp-ctrl-api = {path = "../../drv/sp-ctrl-api"}
sha3 = {version = "0.10", default-features = false}

[build-dependencies]
build-util = {path = "../../build/util"}
idol = {git = "https://github.com/oxidecomputer/idolatry.git"}
anyhow = "1.0.31"
serde = "1"
quote = "1"
sha3 = {version = "0.10", default-features = false}

# This section is here to discourage RLS/rust-analyzer from doing test builds,
# since test builds don't work for cross compilation.
[[bin]]
name = "task-sp-measure"
test = false
bench = false
