# QSPI-0 flash (32MB)
[[flash]]
address = 0x20000000
size = 0x1FF0000
read = true
execute = true

# RAM sections
# TODO(furquan): R/W/X need to be set on a region-by-region basis.
# Code region should have R/X only.
# Other regions in DRAM should not have X.
[[ram]]
address = 0x90000000
size = 0x40000000
read = true
write = true
execute = true
