name = "demo-hifive-inventor"
target = "riscv32imc-unknown-none-elf"
board = "hifive-inventor"
chip = "../../chips/fe310-g003"
stacksize = 896

[kernel]
name = "demo-hifive-inventor"
requires = { flash = 16384, ram = 4096 }
features = []

[tasks.jefe]
name = "task-jefe"
priority = 0
max-sizes = { flash = 16384, ram = 2048 }
start = true
features = ["semihosting-riscv"]
stacksize = 1536

[tasks.rtc]
name = "drv-fe310-rtc"
priority = 1
max-sizes = { flash = 16384, ram = 4096 }
start = true
features = ["semihosting-riscv"]
uses = ["aon_rtc"]
interrupts = { "aon_rtc.irq" = 1 }

[tasks.pong]
name = "task-pong"
priority = 3
max-sizes = { flash = 8192, ram = 1024 }
start = true

[tasks.ping]
name = "task-ping"
priority = 4
max-sizes = { flash = 8192, ram = 1024 }
stacksize = 512
start = true
task-slots = [{peer = "pong"}]

[tasks.idle]
name = "task-idle"
priority = 5
max-sizes = { flash = 256, ram = 256 }
stacksize = 256
start = true
