name = "demo-hifive-inventor"
target = "riscv32imc-unknown-none-elf"
board = "hifive-inventor"
chip = "../../chips/fe310-g003"
stacksize = 896

[kernel]
name = "demo-hifive-inventor"
requires = { flash = 16784, ram = 3472 }
features = []

[tasks.jefe]
name = "task-jefe"
priority = 0
max-sizes = { flash = 16384, ram = 2048 }
start = true
features = ["semihosting-riscv"]
stacksize = 1536

[tasks.ext_int_ctrl]
name = "drv-riscv-plic-server"
priority = 1
max-sizes = { flash = 4096, ram = 2048 }
start = true
features = ["semihosting-riscv"]
uses = ["plic"]
interrupts = { "plic.irq" = 0x1 }

[tasks.ext_int_ctrl.config]
ints = [52]
tasks = ['"rtc"']
notification = [1]
source = ['"rtc"']
pbits = 3

[tasks.rtc]
name = "drv-fe310-rtc"
priority = 2
max-sizes = { flash = 16384, ram = 4096 }
start = true
features = ["semihosting-riscv"]
task-slots = ["ext_int_ctrl"]
uses = ["aon_rtc"]

[tasks.pong]
name = "task-pong"
priority = 3
max-sizes = { flash = 8192, ram = 1024 }
start = true

[tasks.ping]
name = "task-ping"
priority = 4
max-sizes = { flash = 8192, ram = 1024 }
stacksize = 512
start = true
task-slots = [{peer = "pong"}]

[tasks.one_shot]
name = "task-one-shot"
priority = 1
max-sizes = { flash = 8192, ram = 1024 }
stacksize = 512
start = true
features = ["semihosting"]

[tasks.idle]
name = "task-idle"
priority = 5
max-sizes = { flash = 256, ram = 256 }
stacksize = 256
start = true
