[package]
name = "task-secure"
version = "0.1.0"
edition = "2018"

[dependencies]
userlib = {path = "../../sys/userlib", features = ["panic-messages"]}
cortex-m = {version = "0.7", features = ["inline-asm"]}
hypocalls = {path = "../../lib/hypocalls"}
lpc55_flash = {path = "../../lib/lpc55-flash"}

# This section is here to discourage RLS/rust-analyzer from doing test builds,
# since test builds don't work for cross compilation.
[[bin]]
name = "task-secure"
test = false
bench = false
